export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE =  'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

export const GET_ALL_REGISTERED_USERS = 'GET_ALL_REGISTERED_USERS';
export const GOT_ALL_REGISTERED_USERS_SUCCESS = 'GOT_ALL_REGISTERED_USERS_SUCCESS';
export const GOT_ALL_REGISTERED_USERS_FAILURE = 'GOT_ALL_REGISTERED_USERS_FAILURE';


export const GET_POSTS = 'GET_POSTS';
export const GOT_POSTS_SUCCESS = 'GOT_POSTS_SUCCESS';
export const GOT_POSTS_FAILURE = 'GOT_POSTS_FAILURE';


export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const GOT_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS';
export const GOT_SINGLE_POST_FAILURE = 'GET_SINGLE_POST_FAILURE';

export const ADD_POST = 'ADD_POST';
export const ADDED_POST_SUCCESS = 'ADDED_POST_SUCCESS';
export const ADDED_POST_FAILURE = 'ADDED_POST_FAILURE';

export const UPDATE_POST = 'UPDATE_POST';
export const UPDATED_POST_SUCCESS = 'UPDATED_POST_SUCCESS';
export const UPDATED_POST_FAILURE =  'UPDATED_POST_FAILURE';

export const DELETE_POST = 'DELETE_POST';
export const DELETED_POST_SUCCESS = 'DELETED_POST_SUCCESS';
export const DELETED_POST_FAILURE = 'DELETED_POST_FAILURE';